### ISSUE TITLE
Framework for GoogleGenomics/Spark with a CLI and Pipelines

### ISSUE THREAD

**Issue by pgrosu** [googlegenomics/spark-examples#45]
Hi Elmer and Nicole,

What about creating a framework for GoogleGenomics/Spark, and then one can connect via a command-line interface and launch different tasks via classes.  Ideally these will also have the ability to be pipelined together.  

I am thinking about something along the lines of Weka:

http://www.cs.waikato.ac.nz/ml/weka/

You can perform command-line interface (CLI) like this: 

http://weka.wikispaces.com/Primer

You can even have a pipeline like this: 

http://weka.wikispaces.com/Exporting+Charts+from+the+Knowledge+Flow

Maybe you can integrate with Google's Dataflow on this, based on what Cassie mentioned recently.  With a framework you can easily add then a class for caching out the similarity matrices, and then just reloading them as necessary. 

Paul

**Comment by deflaux** [comment]
Its all getting closer http://blog.cloudera.com/blog/2015/01/new-in-cloudera-labs-google-cloud-dataflow-on-apache-spark/

Thanks Paul!
