### ISSUE TITLE
Upgrade to Spark 1.2.0

### ISSUE THREAD

**Issue by elmer-garduno** [googlegenomics/spark-examples#61]
When upgrading to Spark 1.2.0 there is a class compatibility error with com.google.common.base.Optional which is used from utils-java. I opened a bug on Spark to keep track of it.

https://issues.apache.org/jira/browse/SPARK-5052

**Comment by pgrosu** [comment]
Hey Elmer,

Happy New Year!  So I tried what you tested with a older version of Spark, and it seems to get the expected result you were looking for.  Below are the results: 

```
$ javap -classpath ./spark-hadoop-1/spark-1.1.0-bin-hadoop1/lib/spark-assembly-1.1.0-hadoop1.0.4.jar com.google.common.base.Optional
Compiled from "Optional.java"
public abstract class com.google.common.base.Optional<T> implements java.io.Serializable {
  public static <T> com.google.common.base.Optional<T> absent();
  public static <T> com.google.common.base.Optional<T> of(T);
  public static <T> com.google.common.base.Optional<T> fromNullable(T);
  com.google.common.base.Optional();
  public abstract boolean isPresent();
  public abstract T get();
  public abstract T or(T);
  public abstract com.google.common.base.Optional<T> or(com.google.common.base.Optional<? extends T>);
  public abstract T or(com.google.common.base.Supplier<? extends T>);
  public abstract T orNull();
  public abstract java.util.Set<T> asSet();
  public abstract <V> com.google.common.base.Optional<V> transform(com.google.common.base.Function<? super T, V>);
  public abstract boolean equals(java.lang.Object);
  public abstract int hashCode();
  public abstract java.lang.String toString();
  public static <T> java.lang.Iterable<T> presentInstances(java.lang.Iterable<? extends com.google.common.base.Optional<? extends T>>);
}
$ 
```

Maybe sticking with the older version for now might help.  Also on another note, when I cloned the latest version of `spark-examples`, I seem to get the following error:

```
$ sbt "run --client-secrets /home/pgrosu/me/gg_client_secrets/client_secrets_java.json --spark-master local[4]"
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=256M; support was removed in 8.0
[info] Set current project to elmer-guava-optional (in build file:/home/pgrosu/me/gg_spark/test/elmer-guava-optional/)
[info] Updating {file:/home/pgrosu/me/gg_spark/test/elmer-guava-optional/}elmer-guava-optional...
[info] Resolving org.fusesource.jansi#jansi;1.4 ...
[info] Done updating.
java.lang.RuntimeException: No main class detected.
        at scala.sys.package$.error(package.scala:27)
[trace] Stack trace suppressed: run last compile:run for the full output.
[error] (compile:run) No main class detected.
[error] Total time: 2 s, completed Jan 1, 2015 5:29:24 PM
$
```

~p

**Comment by elmer-garduno** [comment]
There is now a patch for this issue, https://github.com/apache/spark/pull/3874.

Spark 1.2.0 has several performance advantages over 1.0 and currently 1.1.1 has a bug that prevents us from running large scale analyses. 

@pgrosu it's strange that the cli above is not asking for the main class? That's still working for me.

**Comment by pgrosu** [comment]
Hi Elmer,

I think I did a little too much celebrating during the New Year, and only ran the clone without the pull.  Running the following steps made it all better :)

```
$ git clone https://github.com/elmer-garduno/spark-examples use_utils_contig
$ cd use_utils_contig/    
$ git pull https://github.com/elmer-garduno/spark-examples use_utils_contig
```

One other thing regarding Spark 1.2.  Once your https://github.com/apache/spark/pull/3874 PR gets merged into the binary Spark distribution for 1.2, then it might be a good thing to add that to the main page below - in terms of release notes:

https://github.com/googlegenomics/spark-examples

Otherwise if you would like users to build Spark with the patch, then that expectation would probably be good to add to that page as well, with possible instructions.

Thanks,
~p

**Comment by deflaux** [comment]
For anyone using bdutil to deploy Spark on Google Compute Engine, the work around for now is to edit the file `bdutil/extensions/spark/spark_env.sh` and roll back the Spark version.  
```
SPARK_HADOOP1_TARBALL_URI='gs://spark-dist/spark-1.1.1-bin-hadoop1.tgz'
SPARK_HADOOP2_TARBALL_URI='gs://spark-dist/spark-1.1.1-bin-hadoop2.4.tgz'
```
Do this before creating the Spark cluster via `./bdutil -e extensions/spark/spark_env.sh deploy`

**Comment by deflaux** [comment]
bdutil now deploys Spark 1.3 https://groups.google.com/forum/#!topic/gcp-hadoop-announce/kz5Oz7uFIi8 as of bdutil 1.2.1
